INHERIT: ../base.yml
docs_dir: ../../src/at
extra:
  alternate:
    - name: Zum Amerikanischen Kochbuch wechseln
      link: /en/
      lang: en
  cite:
    bitterman_die_österreichische_küche: >-
      Bitterman, Adi, Ingrid Pernkopf, und Renate Wagner-Wittula.
      [*Die Österreichische Küche*](https://www.amazon.de/dp/3222140251).
      1. Edition.
      Pichler Verlag in Verlagsgruppe Styria GmbH & Co. KG, 15 September 2018.
    oberndorfer_knödel: >-
      Oberndorfer, Florian, and Zabert Sandmann.
      [*Knödel: Die Besten Klassischen Und Internationalen Knödelrezepte.*](https://www.amazon.de/dp/396584170X)
      München Zs, 2021.
    müller_walser_mein_erstes_kochbuch: >-
      Müller, Anna, and Olga Walser.
      [Mein Erstes Kochbuch: Mit Servierkunde und Nahrungsmittellehre.](https://www.amazon.de/Mein-erstes-Kochbuch-Servierkunde-Nahrungsmittellehre/dp/B0028S3CM0)
      Verlag E. DORNER Gmbh, 2017.
plugins:
  - awesome-pages:
      collapse_single_pages: false
      filename: pages.yml
      strict: true
  - exclude:
      regex:
        - '.*pages.ya?ml'
  - macros
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      css_files:
        - assets/stylesheets/extra.css
  - search:
      lang: de
  - tags:
      tags_file: index.md
site_dir: ../../site/at
site_name: dem Nick seine Rezepte
site_url: http://rezepte.vogt4nick.com/
theme:
  language: de
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: österreich-licht
      toggle:
        icon: material/weather-sunny
        name: In den Dunkelmodus wechseln
    - media: "(prefers-color-scheme: dark)"
      scheme: österreich-dunkel
      toggle:
        icon: material/weather-night
        name: In den Lichtmodus wechseln
