INHERIT: ../base.yml
docs_dir: ../../src/at
extra:
  alternate:
    - name: Zum Amerikanischen Kochbuch wechseln
      link: /en/
      lang: en
plugins:
  - privacy
  - search:
      lang: de
  - tags:
      tags_file: index.md
site_dir: ../../site/at
site_name: dem Nick seine Rezepte
site_url: http://rezepte.vogt4nick.com/
theme:
  language: de
