language: python
python: "3.7"
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws sts assume-role --role-arn arn:aws:iam::491984534845:role/DeployVogt4nickStaticSite --role-session-name deploy-recipes.vogt4nick.com-${TRAVIS_COMMIT}
script:
  - mkdocs build -d output
deploy:
  - provider: script
    role: arn:aws:iam::491984534845:role/DeployVogt4nickStaticSite
    script: aws s3 rm s3://recipes.vogt4nick.com --recursive --region=us-east-1
    skip_cleanup: true
    on:
      branch: recipes.vogt4nick.com
  - provider: s3
    role: arn:aws:iam::491984534845:role/DeployVogt4nickStaticSite
    bucket: recipes.vogt4nick.com
    skip_cleanup: true
    region: us-east-1
    local_dir: output
    default_text_charset: utf-8
    cache_control: no-cache
    acl: public_read
    on:
      branch: recipes.vogt4nick.com
