language: python
python: "3.7"
env:
  - SITEURL=$TRAVIS_BRANCH
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - mkdocs build -d output
deploy:
  - provider: s3
    bucket: recipes-dev.vogt4nick.com
    skip_cleanup: true
    region: us-east-1
    local_dir: output
    default_text_charset: utf-8
    cache_control: no-cache
    acl: public_read
    on:
      branch: recipes-dev.vogt4nick.com
  - provider: s3
    bucket: recipes.vogt4nick.com
    skip_cleanup: true
    region: us-east-1
    local_dir: output
    default_text_charset: utf-8
    cache_control: no-cache
    acl: public_read
    on:
      branch: recipes.vogt4nick.com
