language: python
python: "3.7"
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - mkdir ~/.aws
  - touch ~/.aws/config
  - touch ~/.aws/credentials
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region us-east-1
  - aws configure set DeployVogt4nickStaticSite.role_arn arn:aws:iam::491984534845:role/DeployVogt4nickStaticSite
  - aws configure set DeployVogt4nickStaticSite.source_profile default
  - aws configure get role_arn --profile DeployVogt4nickStaticSite
  - export AWS_PROFILE=DeployVogt4nickStaticSite
script:
  - mkdocs build -d output
deploy:
  - provider: script
    role: arn:aws:iam::491984534845:role/DeployVogt4nickStaticSite
    script: aws s3 rm s3://recipes.vogt4nick.com --recursive --region=us-east-1
    skip_cleanup: true
    on:
      branch: recipes.vogt4nick.com
  - provider: s3
    role: arn:aws:iam::491984534845:role/DeployVogt4nickStaticSite
    bucket: recipes.vogt4nick.com
    skip_cleanup: true
    region: us-east-1
    local_dir: output
    default_text_charset: utf-8
    cache_control: no-cache
    acl: public_read
    on:
      branch: recipes.vogt4nick.com
