site_name: Nick's Recipes
site_description: Nick's Recipes
# repo_url: https://github.com/vogt4nick/recipes.vogt4nick.com
# site_author: Nick Vogt
copyright: Nick Vogt, 2019
docs_dir: recipes
nav:
    - Home: index.md
    - Main Dishes: main-dishes.md
    - Sides: sides.md
    - Desserts: desserts.md
    - Potluck Favorites: potluck-favorites.md
    - Food Lab: food-lab.md
    - Retired Recipes: retired-recipes.md
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "-"
