site_name: Nick's Recipes
docs_dir: src
plugins:
  - search:
      lang:
        - en
  - awesome-pages:
      filename: pages.yml
      collapse_single_pages: false
      strict: true
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    logo: material/silverware
  palette:
    primary: blue
    accent: blue
markdown_extensions:
  # ignore page-level table of contents
  # https://github.com/squidfunk/mkdocs-material/issues/478#issuecomment-578723876
  - toc:
      toc_depth : "1-1"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
google_analytics:
  - UA-109563922-1
  - auto
