site_name: Nick's Recipes
site_description: Nick's Recipes
# repo_url: https://github.com/vogt4nick/recipes.vogt4nick.com
# site_author: Nick Vogt
copyright: Nick Vogt, 2019
docs_dir: recipes
nav:
    - Home: index.md
    - Main Dishes: main-dishes.md
    - Sauces & Sides: sauces-and-sides.md
    - Potluck Favorites: potluck-favorites.md
    - Food Lab: food-lab.md
    - Archive: archive.md
theme: mkdocs
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "-"
