site_name: Nick's Recipes
docs_dir: recipes
nav:
    - Home: index.md
    - Main Dishes: main-dishes.md
    - Sauces & Sides: sauces-and-sides.md
    - Potluck Favorites: potluck-favorites.md
    - Food Lab: food-lab.md
    - Archive: archive.md
theme: mkdocs
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "-"
    - admonition
google_analytics:
    - UA-109563922-1
    - auto
