docs_dir: src/en
site_dir: site/en
site_name: Nick's Recipes
site_url: https://github.com/vogt4nick/recipes.vogt4nick.com
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - privacy
  - search:
      lang: en
theme:
  name: material
  custom_dir: overrides/
  language: en
  favicon: assets/images/shallow-pan-of-food-32x32.png
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - toc.integrate
  icon:
    logo: material/silverware
  include_search_page: false
  search_index_only: true
