site_name: Nick's Recipes
site_url: http://recipes.vogt4nick.com/
docs_dir: src
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  icon:
    logo: material/silverware
  palette:
    primary: blue
    accent: blue
markdown_extensions:
  # ignore page-level table of contents
  # https://github.com/squidfunk/mkdocs-material/issues/478#issuecomment-578723876
  - toc:
      toc_depth : 3
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
plugins:
  - awesome-pages:
      filename: pages.yml
      collapse_single_pages: false
      strict: true
  - macros
  - search:
      lang:
        - en
extra:
  cite:
    bittman_how_to_cook_everything: >-
      Bittman, Mark. [*How to Cook Everything*](https://www.amazon.com/dp/0764578650). Boston, MA: Houghton Mifflin Harcourt, 2019.
    child_french_cooking: >-
      Child, Julia, Louisette Bertholle, and Simone Beck. [*Mastering the Art of French Cooking: Volume 1*](https://www.amazon.com/dp/0375413405). New York, NY: Knopf, 2001.
    hazan_italian_cooking: >-
      Hazan, Marcella, and Karin Kretschmann. [*Essentials of Classic Italian Cooking*](https://www.amazon.com/dp/039458404X). New York, NY: Alfred A. Knopf, 1992.
    ludwinski_sister_pie: >-
      Ludwinski, Lisa, and E. E. Berger. [*Sister Pie: The Recipes & Stories of a Big-hearted Bakery in Detroit*](https://www.amazon.com/dp/0399579761). California: Lorena Jones Books, an Imprint of Crown Publishing Group, 2018.
    perelman_the_smitten_kitchen_cookbook: >-
      Perelman, Deb. [*The Smitten Kitchen Cookbook*](https://www.amazon.com/dp/030759565X/). New York, NY: Alfred A. Knopf, 2017.
google_analytics:
  - UA-109563922-1
  - auto
