site_name: Nick's Recipes
docs_dir: recipes
nav:
  - Menu: index.md
  - Recipes:
    - Archive: recipes/archive.md
    - Beef: recipes/beef.md
    - Breads: recipes/breads.md
    - Desserts: recipes/desserts.md
    - Handhelds: recipes/handhelds.md
    - Meatless: recipes/meatless.md
    - Pork: recipes/pork.md
    - Poultry: recipes/poultry.md
    - Salads: recipes/salads.md
    - Sauces: recipes/sauces.md
    - Shareables: recipes/shareables.md
    - Sides: recipes/sides.md
    - Soups: recipes/soups.md
  - References:
    - Ingredients: references/ingredients.md
    - Styles: references/styles.md
    - Techniques: references/techniques.md
  - About: about.md
theme:
  name: material
  feature:
    tabs: true
  logo:
    icon: restaurant_menu
  palette:
    primary: amber
    accent: amber
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "-"
  - admonition
google_analytics:
  - UA-109563922-1
  - auto
