INHERIT: ../base.yml
docs_dir: ../../src/en
extra:
  alternate:
    - name: Switch to Austrian Cookbook
      link: /at/
      lang: at
  cite:
    bitterman_die_österreichische_küche: >-
      Bitterman, Adi, Ingrid Pernkopf, und Renate Wagner-Wittula.
      [*Die Österreichische Küche*](https://www.amazon.de/dp/3222140251).
      1. Edition.
      Pichler Verlag in Verlagsgruppe Styria GmbH & Co. KG, 15 September 2018.
    bittman_how_to_cook_everything: >-
      Bittman, Mark. [*How to Cook Everything*](https://www.amazon.com/dp/0764578650). 10th Anniversary Edition. Boston, MA: Houghton Mifflin Harcourt, 2008.
    child_french_cooking: >-
      Child, Julia, Louisette Bertholle, and Simone Beck. [*Mastering the Art of French Cooking: Volume 1*](https://www.amazon.com/dp/0375413405). New York, NY: Knopf, 2001.
    hazan_italian_cooking: >-
      Hazan, Marcella, and Karin Kretschmann. [*Essentials of Classic Italian Cooking*](https://www.amazon.com/dp/039458404X). New York, NY: Alfred A. Knopf, 1992.
    ludwinski_sister_pie: >-
      Ludwinski, Lisa, and E. E. Berger. [*Sister Pie: The Recipes & Stories of a Big-hearted Bakery in Detroit*](https://www.amazon.com/dp/0399579761). California: Lorena Jones Books, an Imprint of Crown Publishing Group, 2018.
    perelman_the_smitten_kitchen_cookbook: >-
      Perelman, Deb. [*The Smitten Kitchen Cookbook*](https://www.amazon.com/dp/030759565X/). New York, NY: Alfred A. Knopf, 2017.
site_dir: ../../site/en
site_name: Nick's Recipes
site_url: http://recipes.vogt4nick.com/
theme:
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: msu-licht
      toggle:
        icon: material/weather-sunny
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: msu-dunkel
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
