name: deploy-gh-pages

on: [push]


# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
      - name: Install dependencies
        run: uv sync --no-dev
      - name: Build en site
        run: uv run zensical build -f mkdocs.yml

        # enable upload https://github.com/actions/upload-pages-artifact/tree/v4?tab=readme-ov-file#example-permissions-fix-for-linux
      - name: Fix permissions
        run: |
          chmod -c -R +rX "site/en/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/en

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uvx pre-commit run --all-files

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Deploy to GitHub Pages
    needs: [build, pre-commit]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
