name: Build & Deploy
on: [push]

env:
  MKDOCS_SITE_DIR: ~/site

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # necessary for mkdocs-git-revision-date-localized-plugin
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.11
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Build root site
        run: poetry run mkdocs build -f config/root/mkdocs.yml --strict --site-dir ${{ env.MKDOCS_SITE_DIR }}
      - name: Build at site
        run: poetry run mkdocs build -f config/at/mkdocs.yml --strict --site-dir ${{ env.MKDOCS_SITE_DIR }}/at
      - name: Build en site
        run: poetry run mkdocs build -f config/en/mkdocs.yml --strict --site-dir ${{ env.MKDOCS_SITE_DIR }}/en
      - name: Archive site
        uses: actions/upload-artifact@master
        with:
          name: site
          path: ${{ env.MKDOCS_SITE_DIR }}
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to dev
    needs: [build, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@master
        with:
          name: site
          path: ${{ env.MKDOCS_SITE_DIR }}
      - name: Deploy docs
        run: >-
          aws s3 sync ${{ env.MKDOCS_SITE_DIR }} s3://recipes.dev.vogt4nick.com
          --delete --acl public-read --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to prod
    needs: [build, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@master
        with:
          name: site
          path: ${{ env.MKDOCS_SITE_DIR }}
      - name: Deploy docs
        run: >-
          aws s3 sync ${{ env.MKDOCS_SITE_DIR }} s3://recipes.vogt4nick.com
          --delete --acl public-read --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
