name: Maintenance
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

env:
  MKDOCS_SITE_DIR: ~/site

jobs:
  update_dependencies:
    name: Update build dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install poetry
        run: pipx install poetry==1.1.11
      - uses: actions/setup-python@main
        with:
          python-version: 3.8
          cache: 'poetry'
      - name: Update build dependencies
        run: poetry lock
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: "build(poetry.lock): update build dependencies"
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          title: Update build dependencies
          body: Update the poetry.lock with the latest valid dependencies.
          reviewers: "vogt4nick"
