name: Build & Deploy
on: [push]

env:
  MKDOCS_SITE_DIR: ~/site

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@main
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install --no-dev
      - name: Build root site
        run: poetry run mkdocs build -f config/root/mkdocs.yml --strict --site-dir ${{ env.MKDOCS_SITE_DIR }}
      - name: Build at site
        run: poetry run mkdocs build -f config/at/mkdocs.yml --strict --site-dir ${{ env.MKDOCS_SITE_DIR }}/at
      - name: Build en site
        run: poetry run mkdocs build -f config/en/mkdocs.yml --strict --site-dir ${{ env.MKDOCS_SITE_DIR }}/en
      - name: Archive site
        uses: actions/upload-artifact@master
        with:
          name: site
          path: ${{ env.MKDOCS_SITE_DIR }}
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.11
      - uses: pre-commit/action@main
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    name: Deploy to dev
    needs: [build, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@master
        with:
          name: site
          path: ${{ env.MKDOCS_SITE_DIR }}
      - name: Deploy docs
        run: >-
          aws s3 sync ${{ env.MKDOCS_SITE_DIR }} s3://recipes.dev.vogt4nick.com
          --delete --acl public-read --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
  deploy-prod:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    name: Deploy to prod
    needs: [build, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Download site
        uses: actions/download-artifact@master
        with:
          name: site
          path: ${{ env.MKDOCS_SITE_DIR }}
      - name: Deploy docs
        run: >-
          aws s3 sync ${{ env.MKDOCS_SITE_DIR }} s3://recipes.vogt4nick.com
          --delete --acl public-read --no-progress
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
